var json_Datos_2 = {
"type": "FeatureCollection",
"name": "Datos_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ESTACION": "Beneixama_poble", "Tmin_26 y": -5.3 }, "geometry": { "type": "Point", "coordinates": [ -0.7672, 38.7 ] } },
{ "type": "Feature", "properties": { "ESTACION": "el_Camp_de_Mirra", "Tmin_26 y": -5.9 }, "geometry": { "type": "Point", "coordinates": [ -0.772975, 38.679367 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Salines_poble", "Tmin_26 y": -5.4 }, "geometry": { "type": "Point", "coordinates": [ -0.913364, 38.519933 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_Carrizal", "Tmin_26 y": -5.7 }, "geometry": { "type": "Point", "coordinates": [ -0.875369, 38.595492 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_El_Puerto_Villa Ventin", "Tmin_26 y": -3.3 }, "geometry": { "type": "Point", "coordinates": [ -0.943508, 38.575889 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_Camino_San_Juan", "Tmin_26 y": -7.2 }, "geometry": { "type": "Point", "coordinates": [ -0.865556, 38.625 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_Finca_Cristobalicos", "Tmin_26 y": -5.8 }, "geometry": { "type": "Point", "coordinates": [ -0.880789, 38.61405 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_Colonia_de_Sierra_Salinas", "Tmin_26 y": -4.2 }, "geometry": { "type": "Point", "coordinates": [ -0.9903, 38.526467 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_La_Laguna", "Tmin_26 y": -8.8 }, "geometry": { "type": "Point", "coordinates": [ -0.92, 38.63 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_Las_Virtudes", "Tmin_26 y": -5.9 }, "geometry": { "type": "Point", "coordinates": [ -0.932139, 38.625514 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_ciutat", "Tmin_26 y": -2.2 }, "geometry": { "type": "Point", "coordinates": [ -0.864625, 38.634831 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_la_Safra", "Tmin_26 y": -2.2 }, "geometry": { "type": "Point", "coordinates": [ -0.851625, 38.744208 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_La_Parrala", "Tmin_26 y": -5.3 }, "geometry": { "type": "Point", "coordinates": [ -0.918289, 38.694769 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Villena_Nord.IES_Las_Fuentes", "Tmin_26 y": -7.0 }, "geometry": { "type": "Point", "coordinates": [ -0.8724, 38.6447 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Caudete", "Tmin_26 y": -4.5 }, "geometry": { "type": "Point", "coordinates": [ -0.98, 38.71 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Asp_Poliesportiu", "Tmin_26 y": -2.4 }, "geometry": { "type": "Point", "coordinates": [ -0.794, 38.333 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Novelda_centre", "Tmin_26 y": 2.8 }, "geometry": { "type": "Point", "coordinates": [ -0.765833, 38.383333 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Novelda_est_AEMET", "Tmin_26 y": 2.2 }, "geometry": { "type": "Point", "coordinates": [ -0.7564, 38.3869 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Petrer_centre", "Tmin_26 y": -1.2 }, "geometry": { "type": "Point", "coordinates": [ -0.782253, 38.481653 ] } },
{ "type": "Feature", "properties": { "ESTACION": "el_Pinos_Toscar", "Tmin_26 y": -2.6 }, "geometry": { "type": "Point", "coordinates": [ -1.060722, 38.427414 ] } },
{ "type": "Feature", "properties": { "ESTACION": "el_Pinos_el_Rodriguillo", "Tmin_26 y": -7.7 }, "geometry": { "type": "Point", "coordinates": [ -1.044194, 38.365417 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Hondos de los Frailes", "Tmin_26 y": -2.7 }, "geometry": { "type": "Point", "coordinates": [ -0.927499, 38.272563 ] } },
{ "type": "Feature", "properties": { "ESTACION": "La_Alguena", "Tmin_26 y": -0.7 }, "geometry": { "type": "Point", "coordinates": [ -1.04, 38.35 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Asp_Finca_Alcana", "Tmin_26 y": -0.6 }, "geometry": { "type": "Point", "coordinates": [ -0.84, 38.34 ] } },
{ "type": "Feature", "properties": { "ESTACION": "El_Fondo_De_Les_Neus", "Tmin_26 y": -2.0 }, "geometry": { "type": "Point", "coordinates": [ -0.9, 38.29 ] } },
{ "type": "Feature", "properties": { "ESTACION": "El_Fondo_De_Les_Neus_la_montanosa", "Tmin_26 y": -1.8 }, "geometry": { "type": "Point", "coordinates": [ -0.9, 38.3 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Aspe_Corral_Del_Duque", "Tmin_26 y": -0.6 }, "geometry": { "type": "Point", "coordinates": [ -0.8, 38.34 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Crevillent", "Tmin_26 y": -0.3 }, "geometry": { "type": "Point", "coordinates": [ -0.783158, 38.240831 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Crevillent_el_Realengo", "Tmin_26 y": -0.4 }, "geometry": { "type": "Point", "coordinates": [ -0.801908, 38.200428 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Elx_Sector_V", "Tmin_26 y": 1.8 }, "geometry": { "type": "Point", "coordinates": [ -0.702811, 38.256675 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Elx_Torrellano_CEIP_Antonio_Machado", "Tmin_26 y": 1.0 }, "geometry": { "type": "Point", "coordinates": [ -0.585703, 38.290542 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Elx_Vallverda_Ermita_Vella", "Tmin_26 y": 1.4 }, "geometry": { "type": "Point", "coordinates": [ -0.582506, 38.244458 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Santa_Pola_Ajuntament", "Tmin_26 y": 3.2 }, "geometry": { "type": "Point", "coordinates": [ -0.555639, 38.189944 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Santa_Pola_Gran_Alacant", "Tmin_26 y": 2.3 }, "geometry": { "type": "Point", "coordinates": [ -0.522917, 38.227528 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Elda rotonda M&C", "Tmin_26 y": 0.3 }, "geometry": { "type": "Point", "coordinates": [ -0.800287, 38.474522 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Almorxo", "Tmin_26 y": -2.0 }, "geometry": { "type": "Point", "coordinates": [ -0.780535, 38.504511 ] } },
{ "type": "Feature", "properties": { "ESTACION": "EMA_ELDA", "Tmin_26 y": -1.1 }, "geometry": { "type": "Point", "coordinates": [ -0.790291, 38.48456 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Elda_Camara", "Tmin_26 y": -2.8 }, "geometry": { "type": "Point", "coordinates": [ -0.825422, 38.507208 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Aspe La Nia", "Tmin_26 y": 2.2 }, "geometry": { "type": "Point", "coordinates": [ -0.765203, 38.338165 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Algayat", "Tmin_26 y": 0.6 }, "geometry": { "type": "Point", "coordinates": [ -0.957531, 38.347821 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Nuevo altabix", "Tmin_26 y": 4.2 }, "geometry": { "type": "Point", "coordinates": [ -0.672, 38.276 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Ferriol", "Tmin_26 y": 4.9 }, "geometry": { "type": "Point", "coordinates": [ -0.682, 38.322 ] } },
{ "type": "Feature", "properties": { "ESTACION": "P.N. El Hondo", "Tmin_26 y": 1.9 }, "geometry": { "type": "Point", "coordinates": [ -0.752, 38.178 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Matola", "Tmin_26 y": -3.8 }, "geometry": { "type": "Point", "coordinates": [ -0.765, 38.225 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Valverde", "Tmin_26 y": 0.7 }, "geometry": { "type": "Point", "coordinates": [ -0.609, 38.237 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Banyeres de Mariola (Alberg Ull de Canals)", "Tmin_26 y": -8.3 }, "geometry": { "type": "Point", "coordinates": [ -0.63984, 38.699048 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Banyeres de Mariola (El Barranquet)", "Tmin_26 y": -2.3 }, "geometry": { "type": "Point", "coordinates": [ -0.656763, 38.71916 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Bocairent (Ramba de Mariola)", "Tmin_26 y": -12.8 }, "geometry": { "type": "Point", "coordinates": [ -0.611279, 38.731529 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Pantano de Elda", "Tmin_26 y": -4.6 }, "geometry": { "type": "Point", "coordinates": [ -0.797923, 38.497426 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Elda (Peter Ribes-Rio)", "Tmin_26 y": -2.4 }, "geometry": { "type": "Point", "coordinates": [ -0.806734, 38.458404 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Banyeres de Mariola (Mol� Sol)", "Tmin_26 y": -7.3 }, "geometry": { "type": "Point", "coordinates": [ -0.669892, 38.709807 ] } },
{ "type": "Feature", "properties": { "ESTACION": "Biar (IES Biar)", "Tmin_26 y": -4.4 }, "geometry": { "type": "Point", "coordinates": [ -0.754741, 38.628489 ] } }
]
}
